### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by disser4** [vbezgachev/maxctrl_exporter#21]
Is there a dedicated helm chart for this project?

**Comment by disser4** [comment]
https://github.com/prometheus-community/helm-charts/tree/main/charts

**Comment by vbezgachev** [comment]
Hi @disser4 ! No, due to time constraints, I didn't create a helm chart or anything to deploy into a K8S cluster.

**Comment by disser4** [comment]
We wrote one for maxscale and just added a sidecar to it to scan for metrics.
